// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EnterfoodorderdetailstestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void enterfoodorderdetailstest() {
    driver.get("https://www.foodpanda.com/");
    driver.manage().window().setSize(new Dimension(1366, 728));
    {
      WebElement element = driver.findElement(By.cssSelector(".has-tip:nth-child(8) > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".has-tip:nth-child(7)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".has-tip:nth-child(7) > img")).click();
    driver.findElement(By.cssSelector(".restaurants-search-form__button--full")).click();
    driver.findElement(By.cssSelector(".lane-wrapper:nth-child(1) .vendor-tile-wrapper:nth-child(2) .vendor-picture")).click();
    js.executeScript("window.scrollTo(0,200)");
    js.executeScript("window.scrollTo(0,367)");
    driver.findElement(By.cssSelector("#menu__category-id-0 .dish-card:nth-child(1) > .product-button-overlay")).click();
    js.executeScript("window.scrollTo(0,372)");
    driver.findElement(By.cssSelector("#West\\ Side\\ Garlic28462619-label > .radio-button")).click();
    driver.findElement(By.cssSelector("#West\\ Side\\ Garlic28462636-label > .radio-button")).click();
    driver.findElement(By.cssSelector("#Spicy\\ Habanero26193285-label > .radio-button")).click();
    driver.findElement(By.cssSelector("#Chocolate\\ Lava\\ Cake2401759-label > .checkbox-element")).click();
    driver.findElement(By.cssSelector("#Spicy\\ Habanero26193290-label > .radio-button")).click();
    driver.findElement(By.id("item-modifier-special-instructions")).click();
    {
      WebElement element = driver.findElement(By.id("item-modifier-special-instructions"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("item-modifier-special-instructions")).sendKeys("extra cheese");
    driver.findElement(By.cssSelector(".button-ghost > .fl-interaction-primary")).click();
    driver.findElement(By.cssSelector(".product-add-to-cart-button")).click();
  }
}
